# Site settings
title: Sandip Bhagat
header-img: img/home-bg.jpg
email: sandipbgt@gmail.com
description: "Sandip Bhagat"
baseurl: ""
url: "http://sandipbgt.github.io"
twitter_username: sandipbgt
github_username:  sandipbgt
facebook_username:  sandip02

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
